/**
 * Catálogo de missões, organizado pelos 6 estágios da árvore.
 * O nível N é liberado quando a árvore do jogador alcança o estágio N (users.highest_stage).
 *
 * type 'leitura'   → texto curto com uma fonte para aprofundar.
 * type 'atividade' → investigação prática proposta ao jogador.
 *
 * A `key` é gravada em mission_completions: nunca altere a key de uma missão existente.
 * Além das moedas, toda missão concede 1 fertilizante e 1 proteção (services/missions.js).
 * Fontes: INPE (TerraBrasilis), MapBiomas, Imazon, ISA, Amazônia 2030, Embrapa, INPA e ICMBio.
 */
module.exports = [
  {
    stage: 0,
    theme: 'Fundamentos da floresta e do solo',
    missions: [
      {
        key: 'terra-preta',
        type: 'leitura',
        category: 'biodiversidade',
        coin_reward: 15,
        title: 'Terra Preta de Índio: O Solo Mais Fértil do Planeta',
        description: 'Como povos originários criaram solos ultra-férteis há milhares de anos sem química moderna.',
        content: 'A chamada Terra Preta Arqueológica (TPA) é um solo antrópico extremamente rico em nutrientes, carvão pirogênico (biochar) e cerâmicas pré-colombianas. Criada por sociedades indígenas antigas, ela retém até 3 vezes mais carbono e permanece fértil por séculos, servindo de lição viva para a agricultura regenerativa atual.',
        source_url: 'https://www.embrapa.br/amazonia-oriental',
      },
      {
        key: 'sementes-aladas',
        type: 'leitura',
        category: 'biodiversidade',
        coin_reward: 15,
        title: 'A Dança das Sementes Aladas',
        description: 'Como a Sumaúma dispersa suas sementes através da paina e do vento amazônico.',
        content: 'As sementes da sumaúma são envoltas por uma fibra sedosa e impermeável chamada paina. Essa fibra permite que as sementes flutuem nos ventos da estação seca por dezenas de quilômetros e também boiem nos igarapés durante a cheia, colonizando novas margens de rios.',
        source_url: 'https://inpa.gov.br',
      },
      {
        key: 'bacia-amazonica',
        type: 'leitura',
        category: 'clima',
        coin_reward: 20,
        title: 'Bacia Amazônica: 20% da Água Doce Mundial',
        description: 'A dimensão colossal do sistema fluvial que drena quase metade da América do Sul.',
        content: 'O Rio Amazonas descarrega cerca de 209.000 metros cúbicos de água doce por segundo no Oceano Atlântico. Essa vazão é tão potente que empurra a água salgada do mar por mais de 150 km mar adentro, criando um estuário único de recifes de corais de água turva recém-descobertos.',
        source_url: 'https://www.ana.gov.br',
      },
      {
        key: 'camadas-da-floresta',
        type: 'atividade',
        category: 'biodiversidade',
        coin_reward: 5,
        title: 'Camadas da floresta',
        description: 'Compare o chão, o sub-bosque e a copa. Que diferenças de luz você esperaria encontrar?',
      },
      {
        key: 'sementes-e-germinacao',
        type: 'atividade',
        category: 'biodiversidade',
        coin_reward: 5,
        title: 'Sementes e germinação',
        description: 'Observe uma semente e descreva como água, ar e condições do ambiente participam da germinação.',
      },
      {
        key: 'o-caminho-de-uma-folha-caida',
        type: 'atividade',
        category: 'biodiversidade',
        coin_reward: 5,
        title: 'O caminho de uma folha caída',
        description: 'Investigue a decomposição e escreva como uma folha pode voltar a fazer parte do solo.',
      },
      {
        key: 'raizes-alem-do-tronco',
        type: 'atividade',
        category: 'biodiversidade',
        coin_reward: 5,
        title: 'Raízes além do tronco',
        description: 'Compare as funções de fixação e absorção das raízes. Por que ambas importam para uma muda?',
      },
      {
        key: 'biodiversidade-no-quintal',
        type: 'atividade',
        category: 'biodiversidade',
        coin_reward: 5,
        title: 'Biodiversidade no quintal',
        description: 'Observe um espaço verde sem coletar animais ou plantas. Registre três formas de vida diferentes.',
      },
      {
        key: 'luz-para-uma-pequena-muda',
        type: 'atividade',
        category: 'biodiversidade',
        coin_reward: 5,
        title: 'Luz para uma pequena muda',
        description: 'Compare um local sombreado e um iluminado. Formule uma pergunta sobre o crescimento de plantas nesses ambientes.',
      },
      {
        key: 'seu-primeiro-diario-da-floresta',
        type: 'atividade',
        category: 'biodiversidade',
        coin_reward: 5,
        title: 'Seu primeiro diário da floresta',
        description: 'Reúna três descobertas deste nível e uma pergunta que deseja investigar no próximo.',
      },
    ],
  },
  {
    stage: 1,
    theme: 'Rios voadores e ciclo da água',
    missions: [
      {
        key: 'rios-voadores',
        type: 'leitura',
        category: 'clima',
        coin_reward: 20,
        title: 'Rios Voadores: As Veias d\'Água da América do Sul',
        description: 'Como as árvores amazônicas irrigam as chuvas do Centro-Oeste, Sudeste e Sul do Brasil.',
        content: 'Cada grande árvore amazônica pode bombear mais de 1.000 litros de água para a atmosfera por dia através da evapotranspiração. Essa umidade forma os famosos "Rios Voadores", correntes aéreas de vapor que regulam o clima, a agricultura e as represas de todo o país. Desmatar a Amazônia significa diretamente secar os reservatórios e as torneiras brasileiras.',
        source_url: 'https://inpa.gov.br',
      },
      {
        key: 'bomba-biotica',
        type: 'leitura',
        category: 'clima',
        coin_reward: 25,
        title: 'A Bomba Biótica de Umidade',
        description: 'A física florestal que puxa a umidade do Atlântico para o interior do continente.',
        content: 'Pela teoria da Bomba Biótica desenvolvida pelos físicos Anastassia Makarieva e Victor Gorshkov, florestas contínuas de grande porte criam zonas de baixa pressão atmosférica que puxam ventos úmidos do oceano para dentro do continente. Quando a mata é desmatada, essa sucção quebra, provocando secas extremas.',
        source_url: 'https://inpa.gov.br',
      },
      {
        key: 'igapos',
        type: 'leitura',
        category: 'biodiversidade',
        coin_reward: 20,
        title: 'Igarapés e Florestas de Igapó',
        description: 'Os ecossistemas aquáticos submersos que alimentam a maior ictiofauna do mundo.',
        content: 'As florestas inundadas (igapós e várzeas) passam meses debaixo d\'água. Peixes como o tambaqui se alimentam de frutos silvestres caídos diretamente das copas das árvores, atuando como os principais dispersores de sementes da floresta aquática.',
        source_url: 'https://www.icmbio.gov.br',
      },
      {
        key: 'da-folha-a-atmosfera',
        type: 'atividade',
        category: 'clima',
        coin_reward: 10,
        title: 'Da folha à atmosfera',
        description: 'Investigue a transpiração das plantas e desenhe o percurso da água do solo até a atmosfera.',
      },
      {
        key: 'chuva-que-encontra-a-copa',
        type: 'atividade',
        category: 'clima',
        coin_reward: 10,
        title: 'Chuva que encontra a copa',
        description: 'Observe como folhas e galhos interceptam a chuva. Diferencie interceptação e infiltração.',
      },
      {
        key: 'o-solo-depois-da-chuva',
        type: 'atividade',
        category: 'clima',
        coin_reward: 10,
        title: 'O solo depois da chuva',
        description: 'Compare a infiltração em solo coberto por folhas e em uma superfície impermeável, sem alterar o ambiente.',
      },
      {
        key: 'nascentes-e-vegetacao',
        type: 'atividade',
        category: 'clima',
        coin_reward: 10,
        title: 'Nascentes e vegetação',
        description: 'Investigue a relação entre cobertura vegetal, erosão e proteção de nascentes.',
      },
      {
        key: 'cheia-e-vazante',
        type: 'atividade',
        category: 'clima',
        coin_reward: 10,
        title: 'Cheia e vazante',
        description: 'Pesquise como o ciclo de cheia e vazante influencia o cotidiano de uma comunidade amazônica.',
      },
      {
        key: 'agua-no-seu-cotidiano',
        type: 'atividade',
        category: 'clima',
        coin_reward: 10,
        title: 'Água no seu cotidiano',
        description: 'Identifique três usos de água na sua rotina e escolha uma maneira de evitar desperdício.',
      },
      {
        key: 'um-mapa-do-ciclo-da-agua',
        type: 'atividade',
        category: 'clima',
        coin_reward: 10,
        title: 'Um mapa do ciclo da água',
        description: 'Conecte evaporação, transpiração, condensação, precipitação e infiltração em um esquema.',
      },
    ],
  },
  {
    stage: 2,
    theme: 'Desmatamento e monitoramento por satélite',
    missions: [
      {
        key: 'prodes-deter',
        type: 'leitura',
        category: 'desmatamento',
        coin_reward: 25,
        title: 'PRODES e DETER: Os Olhos no Espaço do INPE',
        description: 'Como satélites brasileiros detectam alertas diários de motosserra e fogo em tempo real.',
        content: 'O sistema DETER do INPE emite alertas diários de alteração na cobertura florestal com resolução para guiar a fiscalização do IBAMA e ICMBio, enquanto o PRODES consolida as taxas anuais oficiais de desmatamento por corte raso. A ciência espacial brasileira é referência global de transparência ambiental.',
        source_url: 'https://terrabrasilis.dpi.inpe.br',
      },
      {
        key: 'ponto-de-nao-retorno',
        type: 'leitura',
        category: 'desmatamento',
        coin_reward: 25,
        title: 'Ponto de Não-Retorno (Tipping Point)',
        description: 'O risco irreversível da savanização da bacia amazônica e seus impactos globais.',
        content: 'Cientistas renomados como Carlos Nobre alertam que se o desmatamento acumulado atingir entre 20% a 25% da cobertura original, a floresta perderá sua capacidade autônoma de reciclar umidade, entrando em um colapso em cadeia chamado de "savanização". Atualmente já ultrapassamos 17% de perda total.',
        source_url: 'https://imazon.org.br',
      },
      {
        key: 'grilagem',
        type: 'leitura',
        category: 'desmatamento',
        coin_reward: 30,
        title: 'Grilagem e o Crime Oculto da Especulação Fundiária',
        description: 'Por que terras públicas não destinadas são o principal alvo de desmatadores ilegais.',
        content: 'Mais de 40% do desmatamento ocorre em florestas públicas ainda não destinadas pelo Estado. Criminosos derrubam e queimam a mata nativa para forjar títulos de posse fraudulentos (grilagem), aguardando anistias políticas em vez de produzir comida.',
        source_url: 'https://imazon.org.br',
      },
      {
        key: 'leia-a-legenda-antes-do-mapa',
        type: 'atividade',
        category: 'desmatamento',
        coin_reward: 15,
        title: 'Leia a legenda antes do mapa',
        description: 'Abra um mapa de cobertura da terra e identifique o significado das cores antes de interpretar os dados.',
      },
      {
        key: 'alerta-nao-e-taxa-anual',
        type: 'atividade',
        category: 'desmatamento',
        coin_reward: 15,
        title: 'Alerta não é taxa anual',
        description: 'Compare a finalidade de um alerta de desmatamento com a de uma estimativa anual consolidada.',
      },
      {
        key: 'datas-mudam-a-interpretacao',
        type: 'atividade',
        category: 'desmatamento',
        coin_reward: 15,
        title: 'Datas mudam a interpretação',
        description: 'Escolha dois mapas do mesmo território em anos diferentes. Verifique se usam a mesma metodologia.',
      },
      {
        key: 'floresta-fragmentada',
        type: 'atividade',
        category: 'desmatamento',
        coin_reward: 15,
        title: 'Floresta fragmentada',
        description: 'Investigue o que são fragmentação e efeito de borda. Descreva uma pergunta sobre seus impactos.',
      },
      {
        key: 'fogo-e-cobertura-vegetal',
        type: 'atividade',
        category: 'desmatamento',
        coin_reward: 15,
        title: 'Fogo e cobertura vegetal',
        description: 'Diferencie um foco de calor detectado por satélite de uma medida de área queimada.',
      },
      {
        key: 'rastreie-uma-noticia-ambiental',
        type: 'atividade',
        category: 'desmatamento',
        coin_reward: 15,
        title: 'Rastreie uma notícia ambiental',
        description: 'Escolha uma notícia sobre desmatamento e encontre a fonte original dos números citados.',
      },
      {
        key: 'seu-primeiro-relatorio-de-observacao',
        type: 'atividade',
        category: 'desmatamento',
        coin_reward: 15,
        title: 'Seu primeiro relatório de observação',
        description: 'Resuma um dado ambiental incluindo fonte, período, local e uma limitação da análise.',
      },
    ],
  },
  {
    stage: 3,
    theme: 'Territórios indígenas e povos tradicionais',
    missions: [
      {
        key: 'terras-indigenas',
        type: 'leitura',
        category: 'povos-tradicionais',
        coin_reward: 30,
        title: 'Terras Indígenas: Os Escudos Mais Eficazes da Terra',
        description: 'Dados de satélite comprovam: onde tem terra indígena demarcada, a floresta fica em pé.',
        content: 'Levantamentos do MapBiomas e Instituto Socioambiental (ISA) mostram que a taxa de desmatamento em Terras Indígenas é inferior a 2%. Yanomami, Kayapó, Ashaninka, Munduruku e centenas de etnias atuam como guardiões da biodiversidade com milênios de manejo sustentável.',
        source_url: 'https://mapbiomas.org',
      },
      {
        key: 'reservas-extrativistas',
        type: 'leitura',
        category: 'povos-tradicionais',
        coin_reward: 25,
        title: 'Reservas Extrativistas e o Legado de Chico Mendes',
        description: 'Seringueiros e castanheiros unindo conservação ambiental e geração de renda.',
        content: 'As Reservas Extrativistas (RESEX) são áreas protegidas de posse comunitária. Nelas, famílias vivem da extração sustentável da borracha, castanha e óleos vegetais sem derrubar uma única árvore. Essa ideia, criada por Chico Mendes na década de 1980, hoje protege milhões de hectares.',
        source_url: 'https://www.socioambiental.org',
      },
      {
        key: 'povos-isolados',
        type: 'leitura',
        category: 'povos-tradicionais',
        coin_reward: 30,
        title: 'Povos Indígenas Isolados: A Última Fronteira Humana',
        description: 'Mais de 100 registros de grupos que escolheram viver sem contato com o mundo externo.',
        content: 'A Amazônia brasileira abriga a maior concentração de povos indígenas isolados do planeta. Eles dependem de florestas contínuas e intactas para sobreviver, sendo extremamente vulneráveis a invasões de garimpeiros, madeireiros e doenças exógenas.',
        source_url: 'https://www.funai.gov.br',
      },
      {
        key: 'diversidade-de-povos-e-linguas',
        type: 'atividade',
        category: 'povos-tradicionais',
        coin_reward: 20,
        title: 'Diversidade de povos e línguas',
        description: 'Pesquise um povo amazônico em uma fonte produzida por seus representantes. Evite generalizar sua cultura para todos os povos.',
      },
      {
        key: 'escutar-antes-de-propor',
        type: 'atividade',
        category: 'povos-tradicionais',
        coin_reward: 20,
        title: 'Escutar antes de propor',
        description: 'Leia uma manifestação pública de uma organização indígena e identifique suas prioridades.',
      },
      {
        key: 'conhecimento-e-autoria',
        type: 'atividade',
        category: 'povos-tradicionais',
        coin_reward: 20,
        title: 'Conhecimento e autoria',
        description: 'Investigue por que reconhecer a autoria coletiva importa ao compartilhar conhecimentos tradicionais.',
      },
      {
        key: 'cartografia-feita-por-comunidades',
        type: 'atividade',
        category: 'povos-tradicionais',
        coin_reward: 20,
        title: 'Cartografia feita por comunidades',
        description: 'Pesquise uma iniciativa de mapeamento participativo e identifique quem decidiu o que seria representado.',
      },
      {
        key: 'calendarios-ligados-ao-territorio',
        type: 'atividade',
        category: 'povos-tradicionais',
        coin_reward: 20,
        title: 'Calendários ligados ao território',
        description: 'Procure um exemplo de calendário sazonal comunitário e observe sua relação com ciclos locais.',
      },
      {
        key: 'juventudes-e-comunicacao-indigena',
        type: 'atividade',
        category: 'povos-tradicionais',
        coin_reward: 20,
        title: 'Juventudes e comunicação indígena',
        description: 'Conheça uma produção de comunicadores indígenas e registre a mensagem central de seus autores.',
      },
      {
        key: 'compartilhar-com-respeito',
        type: 'atividade',
        category: 'povos-tradicionais',
        coin_reward: 20,
        title: 'Compartilhar com respeito',
        description: 'Prepare um resumo de uma produção comunitária, atribua a autoria e preserve o contexto original.',
      },
    ],
  },
  {
    stage: 4,
    theme: 'Sociobioeconomia',
    missions: [
      {
        key: 'sociobioeconomia',
        type: 'leitura',
        category: 'bioeconomia',
        coin_reward: 35,
        title: 'Sociobioeconomia: A Economia do Futuro com a Mata em Pé',
        description: 'Açaí, cacau nativo e castanha gerando bilhões sem derrubar uma árvore sequer.',
        content: 'Estudos do projeto Amazônia 2030 provam que produtos da sociobiodiversidade florestal geram mais empregos e receita de longo prazo por hectare do que a pecuária extensiva degradada. A agrofloresta permite produzir alimentos saudáveis enquanto restaura o solo.',
        source_url: 'https://amazonia2030.org.br',
      },
      {
        key: 'oleos-da-floresta',
        type: 'leitura',
        category: 'bioeconomia',
        coin_reward: 30,
        title: 'Óleos Nobres da Floresta: Andiroba, Copaíba e Murumuru',
        description: 'O valor da farmacopeia e cosmética natural respeitando os conhecimentos locais.',
        content: 'Árvores como a copaíba fornecem óleos medicinais anti-inflamatórios através de perfurações circulares sustentáveis no tronco, que cicatrizam sem matar o espécime. Cooperativas ribeirinhas fornecem insumos para indústrias farmacêuticas e cosméticas globais com repartição justa de benefícios.',
        source_url: 'https://amazonia2030.org.br',
      },
      {
        key: 'creditos-de-carbono',
        type: 'leitura',
        category: 'bioeconomia',
        coin_reward: 35,
        title: 'Créditos de Carbono de Alta Integridade e Jurisdicional',
        description: 'Mecanismos econômicos que remuneram estados e comunidades por evitar desmate.',
        content: 'O mercado de carbono de conservação (REDD+) direciona investimentos internacionais para financiar serviços públicos sustentáveis, monitoramento por drones e cooperativas indígenas em troca de comprovação científica de desmatamento evitado.',
        source_url: 'https://conaveg.mma.gov.br',
      },
      {
        key: 'de-onde-vem-a-castanha',
        type: 'atividade',
        category: 'bioeconomia',
        coin_reward: 25,
        title: 'De onde vem a castanha',
        description: 'Investigue as etapas entre coleta, beneficiamento e comercialização da castanha. Identifique os participantes da cadeia.',
      },
      {
        key: 'agrofloresta-em-camadas',
        type: 'atividade',
        category: 'bioeconomia',
        coin_reward: 25,
        title: 'Agrofloresta em camadas',
        description: 'Pesquise um sistema agroflorestal e observe quais espécies e usos convivem nele.',
      },
      {
        key: 'cooperativas-e-organizacao',
        type: 'atividade',
        category: 'bioeconomia',
        coin_reward: 25,
        title: 'Cooperativas e organização',
        description: 'Escolha uma cooperativa amazônica e descubra como ela apresenta seu trabalho e seus produtos.',
      },
      {
        key: 'origem-e-rastreabilidade',
        type: 'atividade',
        category: 'bioeconomia',
        coin_reward: 25,
        title: 'Origem e rastreabilidade',
        description: 'Compare as informações de origem presentes em dois produtos. Liste o que ainda não é possível verificar.',
      },
      {
        key: 'valor-alem-do-preco',
        type: 'atividade',
        category: 'bioeconomia',
        coin_reward: 25,
        title: 'Valor além do preço',
        description: 'Investigue como transporte, armazenamento e beneficiamento influenciam uma cadeia da sociobiodiversidade.',
      },
      {
        key: 'sazonalidade-dos-alimentos',
        type: 'atividade',
        category: 'bioeconomia',
        coin_reward: 25,
        title: 'Sazonalidade dos alimentos',
        description: 'Escolha um fruto amazônico e pesquise como sua época de colheita afeta a oferta.',
      },
      {
        key: 'uma-escolha-de-consumo-informada',
        type: 'atividade',
        category: 'bioeconomia',
        coin_reward: 25,
        title: 'Uma escolha de consumo informada',
        description: 'Elabore três perguntas sobre origem, produção e remuneração que faria antes de comprar um produto florestal.',
      },
    ],
  },
  {
    stage: 5,
    theme: 'Mobilização e guardiões da floresta',
    missions: [
      {
        key: 'sumauma-monumental',
        type: 'leitura',
        category: 'biodiversidade',
        coin_reward: 40,
        title: 'A Sumaúma Monumental e as Sapopembas Sonoras',
        description: 'A árvore cósmica que conecta a terra e o céu na cosmologia amazônica.',
        content: 'Para os povos indígenas, a Sumaúma é o portal espiritual da floresta. Suas sapopembas (raízes tabulares gigantes) ecoam por quilômetros quando batidas com troncos ocos, servindo como meio ancestral de comunicação entre aldeias ao longo dos rios.',
        source_url: 'https://inpa.gov.br',
      },
      {
        key: 'pacto-amazonia-2030',
        type: 'leitura',
        category: 'clima',
        coin_reward: 40,
        title: 'Pacto Global pela Amazônia: Rumo a 2030 Sem Desmate',
        description: 'A meta de zerar o desmatamento ilegal e recuperar 12 milhões de hectares degradados.',
        content: 'Acordos internacionais como a Declaração de Belém (Cúpula da Amazônia) e metas da COP climática exigem cooperação entre os 8 países que compartilham o bioma para combater o crime organizado transfronteiriço e expandir áreas de proteção integral.',
        source_url: 'https://www.otca.org',
      },
      {
        key: 'mobilizacao-permanente',
        type: 'leitura',
        category: 'mobilizacao',
        coin_reward: 50,
        title: 'Mobilização Permanente: Cada Guardião Conta',
        description: 'Como a consciência individual e coletiva freia a desinformação sobre a Amazônia.',
        content: 'Você alcançou o porte ancestral da Sumaúma! Seu papel agora é difundir a verdade sobre a importância dos rios voadores e apoiar o consumo consciente de cadeias livres de desmatamento.',
        source_url: 'https://mapbiomas.org',
      },
      {
        key: 'planeje-uma-roda-de-conversa',
        type: 'atividade',
        category: 'mobilizacao',
        coin_reward: 30,
        title: 'Planeje uma roda de conversa',
        description: 'Prepare uma conversa sobre um tema aprendido, com perguntas abertas e fontes para consulta.',
      },
      {
        key: 'uma-mensagem-sem-desinformacao',
        type: 'atividade',
        category: 'mobilizacao',
        coin_reward: 30,
        title: 'Uma mensagem sem desinformação',
        description: 'Escreva uma mensagem curta sobre a Amazônia, diferenciando fatos verificados de opiniões.',
      },
      {
        key: 'conheca-uma-iniciativa-local',
        type: 'atividade',
        category: 'mobilizacao',
        coin_reward: 30,
        title: 'Conheça uma iniciativa local',
        description: 'Pesquise uma iniciativa ambiental da sua região e identifique seus objetivos e atividades públicas.',
      },
      {
        key: 'transforme-uma-duvida-em-pesquisa',
        type: 'atividade',
        category: 'mobilizacao',
        coin_reward: 30,
        title: 'Transforme uma dúvida em pesquisa',
        description: 'Escolha uma dúvida que permaneceu e monte um roteiro de pesquisa com fontes e critérios de comparação.',
      },
      {
        key: 'um-projeto-com-objetivo-claro',
        type: 'atividade',
        category: 'mobilizacao',
        coin_reward: 30,
        title: 'Um projeto com objetivo claro',
        description: 'Descreva uma pequena ação educativa, seu público e como você verificaria se o objetivo foi alcançado.',
      },
      {
        key: 'acompanhe-resultados',
        type: 'atividade',
        category: 'mobilizacao',
        coin_reward: 30,
        title: 'Acompanhe resultados',
        description: 'Escolha um projeto público de conservação e procure como ele divulga resultados e limitações.',
      },
      {
        key: 'seu-legado-de-guardiao',
        type: 'atividade',
        category: 'mobilizacao',
        coin_reward: 30,
        title: 'Seu legado de guardião',
        description: 'Revise sua jornada e escreva um plano pessoal de aprendizado e cuidado para o próximo mês.',
      },
    ],
  },
];
